dist: xenial
language: rust
cache: cargo
rust: nightly
matrix:
  include:
  - rust: nightly
  - rust: nightly
    env: "MINVER=true"
install:
- rustup component add rustfmt || true
- if [[ ! -e $TRAVIS_HOME/.cargo/bin/cargo-sweep ]]; then cargo install --version 0.4.1 cargo-sweep; fi
before_script:
- cargo sweep -s
script:
- .travis/build.sh
before_cache:
- cargo sweep -f
